---
- name: install epel-release
  yum:
    name: epel-release
    state: present

- name: install ansible
  yum:
    name: ansible
    state: present

- name: stat ansible configuration file
  stat:
    path: "{{ cfg_file }}"
  register: stat_ansible_config

- name: copy .ansible.cfg to home directory
  copy:
    src: .ansible.cfg
    dest: /home/{{ user }}/.ansible.cfg
    owner: "{{ user }}"
    group: "{{ group }}"
    mode: 0644
  when: stat_ansible_config.stat.exists

- name: stat ansible inventory file
  stat:
    path: "{{ inventory_file }}"
  register: stat_inventory

- name: copy .inventory to home directory
  copy:
    src: .inventory
    dest: /home/{{ user }}/.inventory
    owner: "{{ user }}"
    group: "{{ group }}"
    mode: 0644
  when: stat_inventory.stat.exists
...
